# Site settings
title: Paul Jeanquart
description: 'Keep Calm And Gary On'
url: 'https://pauljeanquart.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Paul Jeanquart'
#  email: code@garybryant.me
 # twitter_username: gabbered
 # facebook_username: gary.bryant.3914
  github_username:  pauljeanquart

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
